# https://manage.auth0.com/dashboard/us/dev-1wng4bqexvtlnxuv/applications/0ztLbWs7kO2OhIBW4I7AVFgPazIl0YB7/settings
apiVersion: v1
kind: Secret
metadata:
  name: auth0-secrets
type: kubernetes.io/dockerconfigjson
stringData:
  AUTH_AUTH0_CLIENT_ID: TODO
  AUTH_AUTH0_CLIENT_SECRET: TODO
  AUTH_AUTH0_DOMAIN_ID: TODO
#  AUTH_AUTH0_AUDIENCE
#  AUTH_AUTH0_CONNECTION
#  AUTH_AUTH0_CONNECTION_SCOPE
  AUTH_SESSION_SECRET: TODO
