site_name: Christophs Demo
site_description: This is a small demo system
repo_url: https://github.com/jerolimov/janus
edit_uri: edit/main/techdocs/christoph-demo/docs

#plugins:
#  - techdocs-core

nav:
  - System: index.md
  - Services:
      - Demo 1: demo1.md
      - Demo 2: demo2.md
      - Demo 3: demo3.md
